import base64
import os

import httpx
from dotenv import load_dotenv

load_dotenv()

DID_API_URL = "https://api.d-id.com"

VOICE_BY_LANGUAGE = {
    "Hebrew": "he-IL-HilaNeural",
    "English": "en-US-JennyNeural",
}


def _get_headers() -> dict:
    api_key = os.environ["DID_API_KEY"]
    encoded = base64.b64encode(f"{api_key}:".encode()).decode()
    return {
        "Authorization": f"Basic {encoded}",
        "Content-Type": "application/json",
    }


def _get_image_url() -> str:
    return os.environ["DID_IMAGE_URL"]


# ---------------------------------------------------------------------------
# Streams API (WebRTC) - Phase 1: Session initialization & WebRTC negotiation (SDP + ICE)
# ---------------------------------------------------------------------------

async def create_stream() -> dict:
    """
    Opens a new stream session with D-ID.
    Returns a dict containing: id, offer (SDP), ice_servers, session_id
    """
    payload = {"source_url": _get_image_url()}

    async with httpx.AsyncClient(timeout=30) as client:
        response = await client.post(
            f"{DID_API_URL}/talks/streams",
            json=payload,
            headers=_get_headers(),
        )
        response.raise_for_status()
        return response.json()


async def send_sdp_answer(stream_id: str, session_id: str, answer: dict) -> None:
    """Sends the SDP answer generated by the browser to D-ID, to complete the WebRTC negotiation."""
    payload = {"session_id": session_id, "answer": answer}

    async with httpx.AsyncClient(timeout=30) as client:
        response = await client.post(
            f"{DID_API_URL}/talks/streams/{stream_id}/sdp",
            json=payload,
            headers=_get_headers(),
        )
        response.raise_for_status()


async def send_ice_candidate(
    stream_id: str,
    session_id: str,
    candidate: str | None,
    sdp_mid: str | None,
    sdp_m_line_index: int | None,
) -> None:
    """
    Sends each ICE candidate discovered by the browser to D-ID (part of WebRTC negotiation).
    candidate=None signals that candidate gathering has finished.
    """
    payload = {
        "session_id": session_id,
        "candidate": candidate,
        "sdpMid": sdp_mid,
        "sdpMLineIndex": sdp_m_line_index,
    }

    async with httpx.AsyncClient(timeout=30) as client:
        response = await client.post(
            f"{DID_API_URL}/talks/streams/{stream_id}/ice",
            json=payload,
            headers=_get_headers(),
        )
        response.raise_for_status()


# ---------------------------------------------------------------------------
# Streams API - Phase 2: Requesting avatar to speak on an open stream
# ---------------------------------------------------------------------------

async def send_stream_text(stream_id: str, session_id: str, text: str, language: str = "Hebrew") -> None:
    """
    Sends text to the avatar while the stream session is active.
    D-ID streams the frames directly via the existing WebRTC track (no waiting for a complete video file).
    """
    voice_id = VOICE_BY_LANGUAGE.get(language.capitalize(), "he-IL-HilaNeural")
    payload = {
        "session_id": session_id,
        "script": {
            "type": "text",
            "input": text,
            "provider": {"type": "microsoft", "voice_id": voice_id},
        },
        "config": {"fluent": True, "pad_audio": 0.0, "stitch": True},
    }

    async with httpx.AsyncClient(timeout=30) as client:
        response = await client.post(
            f"{DID_API_URL}/talks/streams/{stream_id}",
            json=payload,
            headers=_get_headers(),
        )
        response.raise_for_status()


async def close_stream(stream_id: str, session_id: str) -> None:
    """
    Closes the stream session - important to call to avoid wasting D-ID credit minutes.
    If D-ID has already closed the stream (due to inactivity), it returns 400 - this is normal
    and not treated as a critical error.
    """
    payload = {"session_id": session_id}

    async with httpx.AsyncClient(timeout=15) as client:
        response = await client.request(
            "DELETE",
            f"{DID_API_URL}/talks/streams/{stream_id}",
            json=payload,
            headers=_get_headers(),
        )
        if response.status_code == 400:
            # Likely the stream no longer exists or is already closed - this is normal, not an error
            return
        response.raise_for_status()
